apiVersion: v1
kind: Service
metadata:
  name: {{ include "balloray.fullname" . }}-mysyql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
